import { readFileSync } from "node:fs";
const app = readFileSync("src/App.tsx", "utf8");
const presentation = readFileSync("src/presentation.ts", "utf8");
const backend = readFileSync("src-tauri/src/commands/ui.rs", "utf8");
if (!presentation.includes('dashboard: "主控界面"') || !presentation.includes('settings: "设置"') || !presentation.includes('diagnostics: "诊断"')) throw new Error("LB-015 terminology map incomplete");
if (!app.includes("uiText.settings") || !app.includes("uiText.diagnostics")) throw new Error("LB-015 shell does not consume centralized terminology");
if (app.includes('<section className="card"><div className="task-row"')) throw new Error("LB-015 current task is still presented as a card/message");
if (app.includes('disabled>等待系统授权</button>')) throw new Error("LB-015 AwaitingUac exposes a redundant action button");
if (!app.includes("安全隧道")) throw new Error("LB-015 frozen safe-tunnel label is missing");
if (!backend.includes("localbridge-privileged-broker.exe")) throw new Error("LB-015 explicit admin action targets the wrong broker binary");
const permissionBody = backend.slice(backend.indexOf("pub async fn set_permission_mode"), backend.indexOf("fn request_explicit_admin"));
if (!permissionBody.includes("previous == PermissionMode::Elevated") || !permissionBody.includes("requested != PermissionMode::Elevated") || !permissionBody.includes(".privilege()") || !permissionBody.includes(".disable()")) throw new Error("LB-015 leaving administrator mode does not close the privileged gate/Broker");
console.log("LB015_HARDENING=PASS task_inline=true terminology_map=true awaiting_no_button=true broker_name=true leaving_admin_disables_broker=true");
