import { readFileSync } from "node:fs";
import { resolve } from "node:path";
const root=process.env.LOCALBRIDGE_REPO_ROOT||resolve(".");
const c=JSON.parse(readFileSync(resolve(root,"PR_CONTRACTS.json"),"utf8"));
const r=c.rules||{};
const fail=[];
const exact={workspace_context_permission_mode_required:true,workspace_context_workspace_scope_required:true,workspace_context_ordinary_route_token_required:true,workspace_context_elevated_route_available_required:true,workspace_context_privilege_state_summary_required:true,workspace_context_shell_discovery_summary_required:true,workspace_context_capability_snapshot_required:true,public_ninth_core_tool_for_schema36_forbidden:true,shell_ordinary_diagnostics_not_privileged_by_surface_tokens:true,shell_windows_native_syntax_compatibility_required:true,shell_cmd_nul_redirection_required:true,shell_bespoke_dsl_forbidden:true,policy_explain_via_existing_tools_required:true,policy_explain_must_not_execute_or_authorize:true,path_authority_single_localbridge_implementation_required:true,dashboard_permission_mode_row_forbidden:false,dashboard_permission_mode_read_only_row_required:true,dashboard_permission_mode_controls_forbidden:true,dashboard_admin_privilege_status_read_only:false,admin_consent_backend_challenge_not_before_required:true};
if(c.schema_version!==41)fail.push("schema");
for(const [k,v] of Object.entries(exact))if(r[k]!==v)fail.push(k);
for(const [k,v] of Object.entries({workspace_bound_public_path_inputs_must_resolve_within_active_workspace:true,workspace_safe_ordinary_win32_absolute_input_allowed:true,workspace_safe_relative_and_absolute_input_equivalent_after_identity_validation:true,workspace_public_outside_root_absolute_input_forbidden:true,workspace_public_unc_verbatim_posix_ads_input_forbidden:true,workspace_public_reparse_escape_forbidden:true,agent_workflow_workspace_bound_project_path_selector_required:true,schema37_contract_ratified:true}))if(r[k]!==v)fail.push(k);
for(const [k,v] of Object.entries({task_control_cancel_detached_public_session_required:true,task_control_cancel_shared_public_session_terminator_required:true,git_file_metadata_machine_readable_nul_required:true,git_patch_body_and_file_metadata_independent_required:true,command_control_top_level_discoverable_schema_required:true,elevated_exec_top_level_discoverable_schema_required:true,client_hostile_top_level_input_combinator_for_command_and_elevated_forbidden:true,document_rebuild_schema_existing_path_and_content_discoverable_required:true,windows_timeout_term_ctrl_break_forbidden:true,windows_timeout_graceful_then_forced_tree_termination_required:true,windows_timeout_300ms_convergence_test_max_ms:1800,cmd_rmdir_full_ordinary_cleanup_not_privileged_by_surface_syntax:true,schema38_contract_ratified:true,schema38_earliest_owner_pr:"LB-006",schema38_next_g2_review_generation:26,schema38_next_g3_review_generation:16}))if(r[k]!==v)fail.push(k);
for(const [k,v] of Object.entries({workflow_owns_task_lifecycle_required:true,process_backed_task_execution_resource_optional_required:true,process_backed_execution_public_session_to_process_tree_required:true,non_process_task_fake_session_forbidden:true,task_control_remains_high_level_get_cancel_only:true,task_control_ai_session_process_selection_forbidden:true,public_schema_real_mcp_client_projection_acceptance_required:true,public_schema_top_level_discoverable_properties_required:true,server_action_operation_specific_validation_required:true,agent_workflow_orchestration_only_required:true,workspace_context_compact_project_discovery_required:true,workspace_context_cached_discovery_snapshot_required:true,workspace_context_redundant_probe_process_spawn_forbidden:true,workflow_resume_durable_recovery_required:true,retained_output_continuation_recovery_required:true,existing_eight_core_tool_surface_preserved:true,schema39_contract_ratified:true,schema39_earliest_owner_pr:"LB-006",schema39_next_g2_review_generation:27,schema39_next_g3_review_generation:17}))if(r[k]!==v)fail.push(k);
for(const [k,v] of Object.entries({runtime_health_truth_backend_owned_required:true,shell_discovery_runtime_health_independent_required:true,runtime_ready_process_liveness_alone_forbidden:true,runtime_ready_authenticated_mcp_health_required:true,runtime_health_probe_bounded_required:true,private_mcp_transport_faults_trigger_recovery_required:true,process_alive_mcp_unresponsive_recovery_required:true,workspace_context_runtime_hardcoded_ready_forbidden:true,workspace_context_cached_project_discovery_must_not_cache_runtime_health:true,runtime_ready_projection_during_private_mcp_outage_forbidden:true,schema40_contract_ratified:true,schema40_earliest_owner_pr:"LB-006",schema40_preexisting_g2_generation_27_insufficient:true,schema40_preexisting_g3_generation_17_insufficient:true,schema40_next_g2_review_generation:28,schema40_next_g3_review_generation:18}))if(r[k]!==v)fail.push(k);
for(const [k,v] of Object.entries({coding_agent_compatibility_profile:"coding-agent-v1",coding_agent_semantic_profile_required:true,coding_agent_public_api_clone_forbidden:true,coding_agent_embedded_llm_forbidden:true,agent_workflow_primary_coding_entry_required:true,agent_workflow_objective_prepare_without_precomputed_patch_required:true,agent_workflow_host_model_reasoning_boundary_required:true,agent_workflow_cross_call_task_continuity_required:true,durable_coding_task_checkpoint_versioned_required:true,durable_coding_task_files_read_metadata_only_required:true,durable_coding_task_survives_chat_mcp_app_restart_required:true,workspace_context_compact_default_required:true,workspace_context_full_bounded_structured_metadata_required:true,workspace_context_manifest_or_instruction_bulk_dump_forbidden:true,internal_context_service_required:true,internal_context_service_public_tool_forbidden:true,context_service_semantic_symbol_reference_v0_1_required:false,coding_result_domain_specific_data_preserved:true,coding_result_compact_default_required:true,coding_result_large_payload_uses_output_refs_required:true,coding_edit_expected_content_identity_required:true,coding_edit_atomic_write_required:true,coding_edit_file_changed_fail_closed_required:true,coding_edit_missing_target_reuses_not_found_required:true,verification_planner_deterministic_required:true,verification_planner_manifest_or_rule_evidence_required:true,verification_planner_command_guessing_forbidden:true,verification_planner_existing_test_tiers_preserved:true,schema41_contract_ratified:true,schema41_earliest_owner_pr:"LB-006",schema41_next_g2_review_generation:29,schema41_next_g3_review_generation:19,localbridge_agent_api_revision:41}))if(r[k]!==v)fail.push(k);
if(JSON.stringify(r.coding_agent_profile_capabilities)!==JSON.stringify(["workspace_discovery","project_instructions","context_search","command_execution","persistent_task","resume","patch_edit","test_build","git_status_diff","cancellation","output_continuation","typed_errors"]))fail.push("coding_agent_profile_capabilities");
if(JSON.stringify(r.agent_workflow_logical_phases)!==JSON.stringify(["prepare","edit","verify","persist","resume"]))fail.push("agent_workflow_logical_phases");
if(JSON.stringify(r.durable_coding_task_checkpoint_required_fields)!==JSON.stringify(["objective","current_step","next_step","files_read","modified_files","commands","test_results","build_results","failure","output_refs","git_before","git_after"]))fail.push("durable_coding_task_checkpoint_required_fields");
if(JSON.stringify(r.workspace_context_detail_modes)!==JSON.stringify(["compact","full"]))fail.push("workspace_context_detail_modes");
if(JSON.stringify(r.internal_context_service_capabilities)!==JSON.stringify(["discover_instructions","search_text","select_related_files","read_relevant_ranges"]))fail.push("internal_context_service_capabilities");
if(JSON.stringify(r.coding_result_common_envelope_fields)!==JSON.stringify(["ok","state","summary","task_id","warnings","next_step","output_refs","data","error"]))fail.push("coding_result_common_envelope_fields");
if(JSON.stringify(r.coding_edit_internal_primitives)!==JSON.stringify(["read_range","replace_exact","apply_patch","create_file","delete_file","rename_file","mkdir","search_replace"]))fail.push("coding_edit_internal_primitives");
if(JSON.stringify(r.verification_planner_precedence)!==JSON.stringify(["project_instructions","changed_file_targeted_tests","lint_typecheck","project_gate","git_diff_checks"]))fail.push("verification_planner_precedence");
if(JSON.stringify(r.workspace_context_runtime_states)!==JSON.stringify(["ready","recovering","fault"]))fail.push("workspace_context_runtime_states");
if(JSON.stringify(r.schema40_owner_prs)!==JSON.stringify(["LB-006","LB-010","LB-015"]))fail.push("schema40_owner_prs");
if(JSON.stringify(r.schema41_owner_prs)!==JSON.stringify(["LB-006"]))fail.push("schema41_owner_prs");
if(JSON.stringify(r.public_process_lifecycle_states)!==JSON.stringify(["running","completed","failed","cancelled","timed_out","lost"]))fail.push("public_process_lifecycle_states");
if(JSON.stringify(r.workspace_context_compact_project_discovery_fields)!==JSON.stringify(["project_name","project_type","project_version","git_branch","git_dirty","git_changed_count","git_root","package_manager","build_system","test_system","important_files","instructions","runtime_availability","trusted_shells","permission_mode","current_task"]))fail.push("workspace_context_compact_project_discovery_fields");
for(const k of ["workspace_bound_public_path_inputs_relative_only","workspace_public_absolute_path_input_forbidden","agent_workflow_workspace_relative_project_path_selector_required"])if(Object.hasOwn(r,k))fail.push("legacy:"+k);
const core=["workspace_context","agent_workflow","exec_command","command_control","task_control","git_workflow","document_workflow","view_image"];
if(JSON.stringify(r.localbridge_agent_api_v1_core_tools)!==JSON.stringify(core))fail.push("core-tools");
for(const e of ["PolicyDenied","WorkspaceDenied","RuntimeUnavailable","InvalidShellSyntax","PrivilegedRouteUnavailable","ProcessTimedOut"])if(!(r.stable_public_error_codes||[]).includes(e))fail.push("error:"+e);
for(const e of ["FileChanged","PatchConflict","AmbiguousMatch"])if(!(r.public_typed_error_taxonomy||[]).includes(e))fail.push("coding-error:"+e);
const facade=readFileSync(resolve(root,"src-tauri/src/mcp/facade.rs"),"utf8");
for(const m of ["permission_mode","workspace_scope","ordinary_route_token","elevated_route_available","shell_discovery","capabilities","PrivilegedRouteUnavailable","InvalidShellSyntax"])if(!facade.includes(m))fail.push("workspace-context:"+m);
const policy=readFileSync(resolve(root,"src-tauri/src/mcp/policy.rs"),"utf8");
for(const m of ["powershell_readonly_command_discovery","cmd_invocation_requires_review","full_style_diagnostics_are_not_privileged_by_argument_tokens"])if(!policy.includes(m))fail.push("shell-classifier:"+m);
const state=JSON.parse(readFileSync(resolve(root,"PR_INDEX.json"),"utf8"));
const pr=(id)=>state.prs.find((item)=>item.id===id);
const g3Reopened=state.execution?.current_group==="G3" || ["READY","IN_PROGRESS","REWORK_REQUIRED","PASS"].includes(pr("LB-015")?.status);
if(g3Reopened){
  const app=readFileSync(resolve(root,"src/App.tsx"),"utf8");
  if(!app.includes(">权限模式</span>")||!app.includes("accessText[projection.permission]"))fail.push("dashboard-permission-row");
  if(app.includes(">管理员权限</span>"))fail.push("dashboard-privilege-row");
}
const lb016Active=["READY","IN_PROGRESS","REWORK_REQUIRED","PASS"].includes(pr("LB-016")?.status);
if(lb016Active){
  const ui=readFileSync(resolve(root,"src-tauri/src/commands/ui.rs"),"utf8");
  if(!/(challenge|not_before|not-before)/i.test(ui))fail.push("backend-admin-consent-challenge");
}
if(fail.length){console.error("ARCH-034 "+fail.join("|"));process.exit(1);}
console.log("ARCH-034 PASS");
