import { readFileSync, existsSync } from "node:fs";
const ui = readFileSync("src/features/onboarding/Onboarding.tsx","utf8");
const api = readFileSync("src/features/onboarding/api.ts","utf8");
const css = readFileSync("src/features/onboarding/onboarding.css","utf8");
const frame = readFileSync("src/components/WizardFrame.tsx","utf8");
const readiness = readFileSync("src/components/ReadinessCheck.tsx","utf8");
const backend = readFileSync("src-tauri/src/commands/onboarding.rs","utf8");
const permissionBackend = readFileSync("src-tauri/src/commands/ui.rs","utf8");
const lib = readFileSync("src-tauri/src/lib.rs","utf8");
const bridge = readFileSync("src/bridge.ts","utf8");
const app = readFileSync("src/App.tsx","utf8");
const runtimeE2e = readFileSync("tests/e2e/onboarding/fixed_window_runtime_e2e.mjs","utf8");
const auth = JSON.parse(readFileSync("scripts/authorization-records/LB-016.json","utf8"));
if (!frame.includes("/ 5") || frame.includes("/ 6")) throw new Error("LB-016 WizardFrame is not strict five-screen");
for (const pair of [[1,"简单设置 即可开始"],[3,"项目与权限"],[4,"创建自定义插件"],[5,"启动检查"]]) if (!ui.includes(`step={${pair[0]}}`) || !ui.includes(`title="${pair[1]}"`)) throw new Error(`LB-016 screen missing: ${pair[0]} ${pair[1]}`);
if (!ui.includes('step={2}') || !ui.includes('>Tunnel ID<') || !ui.includes('>Runtime API Key<')) throw new Error("LB-016 Screen 2 OpenAI fields drifted");
if (!ui.includes('const KEY_HINT = "Runtime API Key 仅保存在 Windows 安全凭据中。"') || ui.includes("不会写入配置文件、日志、命令行或浏览器存储")) throw new Error("LB-016 Screen 2 Runtime API Key hint is not the exact one-line contract");
if (!ui.includes('useState(initial.tunnelId ?? "")')) throw new Error("LB-016 Screen 2 does not prefill the persisted Tunnel ID");
if (!api.includes("runtimeKeyLength: number | null") || !backend.includes("runtime_key_length: Option<usize>") || !backend.includes("secret.expose_secret().chars().count()")) throw new Error("LB-016 saved Runtime API Key length-only projection missing");
const rustStateStart = backend.indexOf("pub struct OnboardingState");
const rustStateEnd = backend.indexOf("}", rustStateStart);
const rustState = backend.slice(rustStateStart, rustStateEnd + 1);
if (/\bruntime_key\s*:\s*(?:String|SecretString|Option<String>)/.test(rustState) || /runtime_api_key/.test(rustState)) throw new Error("LB-016 backend OnboardingState exposes Runtime API Key plaintext");
const apiStateStart = api.indexOf("export interface OnboardingState");
const apiStateEnd = api.indexOf("}", apiStateStart);
const apiState = api.slice(apiStateStart, apiStateEnd + 1);
if (/\bruntimeKey\s*:\s*string/.test(apiState) || /runtimeApiKey/.test(apiState)) throw new Error("LB-016 frontend OnboardingState exposes Runtime API Key plaintext");
if (!ui.includes('"*".repeat(state.runtimeKeyLength)') || !ui.includes('"已安全保存至windows安全凭据"')) throw new Error("LB-016 saved Runtime API Key mask/status contract missing");
if (!ui.includes('runtimeKeyEditing ? runtimeKey : ""')) throw new Error("LB-016 untouched saved-key mask could be submitted as replacement data");
if (!ui.includes("onBeforeInput={handleRuntimeKeyBeforeInput}") || !ui.includes("onPaste={handleRuntimeKeyPaste}")) throw new Error("LB-016 saved-key display mask is not separated from replacement input");
for (const forbidden of ["Local Bridge 使用确认","step === 6","step={6}"]) if (ui.includes(forbidden)) throw new Error(`LB-016 obsolete sixth screen remains: ${forbidden}`);
if (!api.includes('prepareProject:') || !api.includes('"prepare_onboarding_project"') || ui.includes("READY_POLL_ATTEMPTS") || ui.includes("READY_POLL_INTERVAL_MS") || ui.includes("startProject(") || /setInterval\s*\(/.test(ui)) throw new Error("LB-016 React still owns runtime/readiness lifecycle");
for (const required of ["projection.projectionRevision", "bridge.waitForProjectionChange(revision)", "while (!cancelled)"]) if (!ui.includes(required)) throw new Error(`LB-016 backend wake-driven readiness observation missing: ${required}`);
for (const required of ["pub async fn prepare_onboarding_project","tauri::async_runtime::spawn_blocking","ui::set_permission_mode(mode, app.clone()).await?","current.readiness.all_ready()","Duration::from_millis(250)"]) if (!backend.includes(required)) throw new Error(`LB-016 backend-owned Screen3 readiness missing: ${required}`);
if (!ui.includes("await bridge.setAccess(mode)") || !permissionBackend.includes("enable_from_explicit_user_action") || !permissionBackend.includes("!matches!(lifecycle.privilege().state(), PrivilegeState::Active")) throw new Error("LB-016 administrator selection/reselection is not the explicit UAC action");
for (const forbidden of ["enable_admin","disable_admin","enableAdmin","disableAdmin","启用管理员权限"]) if (`${ui}\n${bridge}\n${app}\n${lib}`.includes(forbidden)) throw new Error(`LB-016 separate administrator enable surface remains: ${forbidden}`);
if (!css.includes(".choice.onboarding-permission{height:auto;min-height:96px;") || !css.includes("padding:15px 16px")) throw new Error("LB-016 Screen3 permission-card specificity/height/padding contract missing");
for (const marker of ['"permission-geometry"', "getBoundingClientRect()", "document.createRange()", "getClientRects()", "ordinaryHeight * 2", "permissionGeometryFailed"]) if (!ui.includes(marker)) throw new Error(`LB-016 real Screen3 rendered-geometry self-gate missing: ${marker}`);
if (!runtimeE2e.includes('?lb016-e2e=permission-geometry')) throw new Error("LB-016 native onboarding E2E does not open the real Screen3 geometry gate");
if (!ui.includes('title="创建自定义插件"') || !ui.includes('在插件设置页面最底端，打开“开发者模式”') || !ui.includes('打开插件管理页后，选择隧道并选择刚刚添加的Tunel，创建插件')) throw new Error("LB-016 Screen4 exact copy drifted");
for (const required of ["open_chatgpt_plugins_settings","https://chatgpt.com/plugins#settings/Plugins","open_chatgpt_custom_connector_settings","https://chatgpt.com/plugins#settings/Connectors?create-connector=true&redirectAfter=%2Fplugins"]) if (!backend.includes(required)) throw new Error(`LB-016 fixed Rust browser allowlist missing: ${required}`);
if (!css.includes(".onboarding-plugin-top-action,.onboarding-plugin-management{display:flex;justify-content:flex-start}")) throw new Error("LB-016 Screen4 browser actions are not left aligned");
if ((ui.match(/onboarding-info-row/g)||[]).length !== 2 || !ui.includes('>Local Bridge<') || !ui.includes('>Tunnel ID<') || ui.includes('本地服务</span>')) throw new Error("LB-016 Screen4 is not exact two-row persisted identity");
if (!ui.includes("window.setTimeout(() =>") || !ui.includes("}, 3000)") || !ui.includes('copiedRows.name ? "已复制" : "复制"') || !ui.includes('copiedRows.tunnel ? "已复制" : "复制"')) throw new Error("LB-016 copy feedback is not stable three-second per row");
for (const step of [2,3,4,5]) if (!ui.includes(`setStep(${step-1})`)) throw new Error(`LB-016 Screen ${step} lacks back path`);
for (const label of ["本地运行环境","编码服务","OpenAI Tunnel"]) if (!ui.includes(`label="${label}"`)) throw new Error(`LB-016 Screen5 check missing: ${label}`);
if (!readiness.includes("ServiceStatusDot")) throw new Error("LB-016 Screen5 does not share typed status-dot presentation");
for (const text of ["等待检查","正在检查","已通过","需要处理"]) if (!readiness.includes(text)) throw new Error(`LB-016 Screen5 status wording missing: ${text}`);
if (!existsSync("tests/e2e/onboarding/fixed_window_runtime_e2e.mjs")) throw new Error("LB-016 real fixed-window E2E missing");
for (const command of ["get_onboarding_state","save_onboarding_connection","choose_onboarding_workspace_folder","open_chatgpt_plugins_settings","open_chatgpt_custom_connector_settings","complete_onboarding"]) {
  const start = backend.indexOf('pub async fn ' + command);
  if (start < 0) throw new Error('LB-016 blocking onboarding Tauri command remains: ' + command);
  const next = backend.indexOf('pub async fn ', start + 12);
  const body = backend.slice(start, next < 0 ? backend.length : next);
  if (!body.includes('spawn_blocking')) throw new Error('LB-016 onboarding command lacks worker boundary: ' + command);
}
const latest=auth.records.find(r=>r.authorization_id==="EXEC-PREAUTH-LB016-014"); if(!latest || latest.user_audit_status!=="PENDING") throw new Error("LB-016 historical authorization audit state changed");
console.log("LB016_CONTRACT=PASS screens=5 saved_connection_projection=length_only runtime_key_plaintext_frontend=false saved_key_mask=length_exact untouched_mask_retained=true backend_owned_readiness=true wake_driven_projection=true ui_blocking_boundary=true admin_selection_uac=true permission_geometry=runtime_gated screen4_exact=true screen5_shared_typed_state=true human_visual_gate=pending");
