import { readFileSync, existsSync } from "node:fs";
const ui = readFileSync("src/features/onboarding/Onboarding.tsx","utf8");
const api = readFileSync("src/features/onboarding/api.ts","utf8");
const css = readFileSync("src/features/onboarding/onboarding.css","utf8");
const frame = readFileSync("src/components/WizardFrame.tsx","utf8");
const readiness = readFileSync("src/components/ReadinessCheck.tsx","utf8");
const adminWarning = readFileSync("src/components/AdminModeWarning.tsx","utf8");
const backend = readFileSync("src-tauri/src/commands/onboarding.rs","utf8");
const permissionBackend = readFileSync("src-tauri/src/commands/ui.rs","utf8");
const lifecycleBackend = readFileSync("src-tauri/src/app/background.rs","utf8");
const controlPlane = readFileSync("src-tauri/src/control_plane/snapshot.rs","utf8");
const lib = readFileSync("src-tauri/src/lib.rs","utf8");
const bridge = readFileSync("src/bridge.ts","utf8");
const app = readFileSync("src/App.tsx","utf8");
const runtimeE2e = readFileSync("tests/e2e/onboarding/fixed_window_runtime_e2e.mjs","utf8");
const auth = JSON.parse(readFileSync("scripts/authorization-records/LB-016.json","utf8"));
if (!frame.includes("/ 5") || frame.includes("/ 6")) throw new Error("LB-016 WizardFrame is not strict five-screen");
for (const pair of [[1,"简单设置 即可开始"],[3,"项目与权限"],[4,"创建自定义插件"],[5,"启动检查"]]) if (!ui.includes(`step={${pair[0]}}`) || !ui.includes(`title="${pair[1]}"`)) throw new Error(`LB-016 screen missing: ${pair[0]} ${pair[1]}`);
if (!ui.includes('step={2}') || !ui.includes('>Tunnel ID<') || !ui.includes('>Runtime API Key<')) throw new Error("LB-016 Screen 2 OpenAI fields drifted");
if (!ui.includes('const KEY_HINT = "Runtime API Key 仅保存在 Windows 安全凭据中。"') || ui.includes("不会写入配置文件、日志、命令行或浏览器存储")) throw new Error("LB-016 Screen 2 Runtime API Key hint is not the exact one-line contract");
if (!ui.includes('useState(initial.tunnelId ?? "")')) throw new Error("LB-016 Screen 2 does not prefill the persisted Tunnel ID");
if (!api.includes("runtimeKeyLength: number | null") || !backend.includes("runtime_key_length: Option<usize>") || !backend.includes("settings.and_then(|settings| settings.runtime_key_length)") || !permissionBackend.includes("secret.expose_secret().chars().count()")) throw new Error("LB-016 saved Runtime API Key length-only snapshot projection missing");
const rustStateStart = backend.indexOf("pub struct OnboardingState");
const rustStateEnd = backend.indexOf("}", rustStateStart);
const rustState = backend.slice(rustStateStart, rustStateEnd + 1);
if (/\bruntime_key\s*:\s*(?:String|SecretString|Option<String>)/.test(rustState) || /runtime_api_key/.test(rustState)) throw new Error("LB-016 backend OnboardingState exposes Runtime API Key plaintext");
const apiStateStart = api.indexOf("export interface OnboardingState");
const apiStateEnd = api.indexOf("}", apiStateStart);
const apiState = api.slice(apiStateStart, apiStateEnd + 1);
if (/\bruntimeKey\s*:\s*string/.test(apiState) || /runtimeApiKey/.test(apiState)) throw new Error("LB-016 frontend OnboardingState exposes Runtime API Key plaintext");
if (!apiState.includes("projectionRevision: number") || apiState.includes("permission: AccessCode")) throw new Error("LB-016 onboarding DTO duplicates or omits revisioned control-plane state");
for (const marker of ["projection_revision: u64", "snapshot.revision", "snapshot.onboarding_readiness()"] ) if (!backend.includes(marker)) throw new Error(`LB-016 backend onboarding projection does not derive from one snapshot: ${marker}`);
if (rustState.includes("permission:") || backend.includes("authority.desired")) throw new Error("LB-016 backend onboarding projection retains a parallel permission value");
if (ui.includes('useState<AccessCode>("edit")') || ui.includes("setPermission(")) throw new Error("LB-016 React still owns a parallel live permission value");
for (const marker of ["main?.effectivePermission === mode", "nextMain.effectivePermission !== mode", 'nextMain.permissionReconciliation !== "converged"', "main?.onboardingReady === true"] ) if (!ui.includes(marker)) throw new Error(`LB-016 permission/readiness controls do not use the effective control-plane projection: ${marker}`);
if (ui.includes("state.permission")) throw new Error("LB-016 onboarding still consumes its obsolete permission projection");
for (const marker of ["pub struct OnboardingReadiness", "ProjectionAvailability::Ready", "runtime.is_stale()", "pub fn onboarding_readiness"] ) if (!controlPlane.includes(marker)) throw new Error(`LB-016 shared control-plane readiness projection missing: ${marker}`);
if (!ui.includes('"*".repeat(state.runtimeKeyLength)') || !ui.includes('"已安全保存至windows安全凭据"')) throw new Error("LB-016 saved Runtime API Key mask/status contract missing");
if (!ui.includes('runtimeKeyEditing ? runtimeKey : ""')) throw new Error("LB-016 untouched saved-key mask could be submitted as replacement data");
if (!ui.includes("onBeforeInput={handleRuntimeKeyBeforeInput}") || !ui.includes("onPaste={handleRuntimeKeyPaste}")) throw new Error("LB-016 saved-key display mask is not separated from replacement input");
for (const forbidden of ["Local Bridge 使用确认","step === 6","step={6}"]) if (ui.includes(forbidden)) throw new Error(`LB-016 obsolete sixth screen remains: ${forbidden}`);
if (!api.includes('prepareProject:') || !api.includes('"prepare_onboarding_project"') || ui.includes("READY_POLL_ATTEMPTS") || ui.includes("READY_POLL_INTERVAL_MS") || ui.includes("startProject(") || /setInterval\s*\(/.test(ui)) throw new Error("LB-016 React still owns runtime/readiness lifecycle");
for (const required of ["projection.projectionRevision", "bridge.waitForProjectionChange(revision)", "while (!cancelled)"]) if (!ui.includes(required)) throw new Error(`LB-016 backend wake-driven readiness observation missing: ${required}`);
for (const required of ["pub async fn prepare_onboarding_project","tauri::async_runtime::spawn_blocking","current.readiness.all_ready()","Duration::from_millis(250)"]) if (!backend.includes(required)) throw new Error(`LB-016 backend-owned Screen3 readiness missing: ${required}`);
const prepareStart = backend.indexOf("pub async fn prepare_onboarding_project");
const prepareEnd = backend.indexOf("pub async fn complete_onboarding", prepareStart);
if (backend.slice(prepareStart, prepareEnd).includes("set_permission_mode")) throw new Error("LB-016 project preparation still duplicates the permission writer");
if (!ui.includes("await bridge.setAccess(mode)") || !lifecycleBackend.includes("enable_from_explicit_user_action") || !permissionBackend.includes("let privilege_active =") || !permissionBackend.includes("matches!(lifecycle.privilege().state(), PrivilegeState::Active { .. })") || !permissionBackend.includes("&& !privilege_active") || !permissionBackend.includes("reconcile_explicit_permission(&lifecycle)?")) throw new Error("LB-016 administrator selection/reselection is not the consent-gated lifecycle reconciliation action");
for (const forbidden of ["enable_admin","disable_admin","enableAdmin","disableAdmin","启用管理员权限"]) if (`${ui}\n${bridge}\n${app}\n${lib}`.includes(forbidden)) throw new Error(`LB-016 separate administrator enable surface remains: ${forbidden}`);
if (!css.includes(".onboarding-permissions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;align-items:stretch}") || !css.includes(".choice.onboarding-permission{width:100%;height:100%;min-width:0;padding:15px 16px")) throw new Error("LB-016 Screen3 PermissionMode group is not the symmetric equal-three-column contract");
for (const marker of ['"permission-geometry"', "getBoundingClientRect()", "document.createRange()", "getClientRects()", "Math.max(...widths) - Math.min(...widths) <= 0.5", "Math.max(...heights) - Math.min(...heights) <= 0.5", "Math.abs(gaps[0] - gaps[1]) <= 0.5", "lineBoxesInside(button, button.querySelector(\"strong\"))", "lineBoxesInside(button, button.querySelector(\"small\"))", "permissionGeometryFailed"]) if (!ui.includes(marker)) throw new Error(`LB-016 real Screen3 equal-thirds rendered-geometry self-gate missing: ${marker}`);
if (!runtimeE2e.includes('?lb016-e2e=permission-geometry')) throw new Error("LB-016 native onboarding E2E does not open the real Screen3 geometry gate");
for (const marker of ["get_webview_window(MAIN_WINDOW_LABEL)", "is_none()", "ensure_main_window(window.app_handle())", "close_destroy=true", "reopen_recreates_webview=true", "keep_background_process_alive", "api.prevent_exit()"]) if (!readFileSync("src-tauri/src/main.rs", "utf8").includes(marker)) throw new Error(`LB-016 native close/reopen WebView lifecycle missing: ${marker}`);
for (const text of ["启用管理员权限后，错误或恶意操作可能导致：","删除或覆盖重要文件","修改系统关键配置","软件或系统无法正常启动","数据永久丢失","安全机制被绕过或关闭","凭据、密钥等敏感信息泄露","恶意程序获得更高权限","系统被破坏，严重时可能需要重装 Windows","仅在你明确理解操作后果时授权。"]) if (!adminWarning.includes(text)) throw new Error(`LB-016 shared administrator warning exact copy missing: ${text}`);
for (const marker of ["adminWarningRemainingSeconds","notBeforeUnixMs.current","Date.now()",'event.key === "Escape"',"crypto.randomUUID()","bridge.beginAdminConsent(challengeId.current)","bridge.cancelAdminConsent(challengeId.current)","bridge.confirmAdminConsent(challengeId.current)","backendChallengeReady","disabled={!backendChallengeReady || remainingSeconds > 0}",' : "确认"']) if (!adminWarning.includes(marker)) throw new Error(`LB-016 shared administrator warning presentation gate missing: ${marker}`);
for (const marker of ["ADMIN_CONSENT_DURATION", "Duration::from_millis(3000)", "struct PendingAdminConsent", "challenge_id: String", "not_before: Instant", "confirmed: bool", "AdminConsentGate", "begin_admin_consent_challenge", "cancel_admin_consent_challenge", "confirm_admin_consent_challenge", "consume_confirmed_admin_consent()", "管理员确认无效或尚未完成", "admin_consent_gate_rejects_early_and_consumes_exact_boundary", "admin_consent_gate_fresh_begin_resets_full_deadline", "admin_consent_gate_stale_identity_cannot_confirm_or_cancel_newer_challenge", "admin_consent_gate_matching_cancel_invalidates_challenge"]) if (!permissionBackend.includes(marker)) throw new Error(`LB-016 backend administrator consent gate missing: ${marker}`);
const consentCheck = permissionBackend.indexOf("&& !consume_confirmed_admin_consent()");
const settingsMutation = permissionBackend.indexOf("let (store, mut data) = load_app_data(&app)?;", permissionBackend.indexOf("pub async fn set_permission_mode"));
if (consentCheck < 0 || settingsMutation < 0 || consentCheck > settingsMutation) throw new Error("LB-016 backend consent gate does not fail closed before settings/runtime/Broker side effects");
if (!ui.includes('title="创建自定义插件"') || !ui.includes('在插件设置页面最底端，打开“开发者模式”') || !ui.includes('打开新建插件页后，选择隧道并选择刚刚添加的Tunel，创建插件') || !ui.includes('>打开新建插件页</button>')) throw new Error("LB-016 Screen4 exact copy drifted");
for (const required of ["open_chatgpt_plugins_settings","https://chatgpt.com/plugins#settings/Plugins","open_chatgpt_custom_connector_settings","https://chatgpt.com/plugins#settings/Connectors?create-connector=true&redirectAfter=%2Fplugins"]) if (!backend.includes(required)) throw new Error(`LB-016 fixed Rust browser allowlist missing: ${required}`);
if (!css.includes(".onboarding-plugin-top-action,.onboarding-plugin-management{display:flex;justify-content:flex-start}")) throw new Error("LB-016 Screen4 browser actions are not left aligned");
if ((ui.match(/onboarding-info-row/g)||[]).length !== 2 || !ui.includes('>Local Bridge<') || !ui.includes('>Tunnel ID<') || ui.includes('本地服务</span>')) throw new Error("LB-016 Screen4 is not exact two-row persisted identity");
const connectorAction = ui.indexOf('>打开新建插件页</button>');
const identityRows = ui.indexOf('<div className="onboarding-plugin-info">');
if (connectorAction < 0 || identityRows < 0 || connectorAction > identityRows) throw new Error("LB-016 打开新建插件页 action is not above identity rows");
const compactCss = css.replace(/\s+/g, "");
if (!compactCss.includes(".onboarding-info-row{display:grid;grid-template-columns:6emminmax(0,1fr)max-content") || !compactCss.includes(".onboarding-copy-action{justify-self:end}")) throw new Error("LB-016 Screen4 identity columns are not aligned");
if (!ui.includes("window.setTimeout(() =>") || !ui.includes("}, 3000)") || !ui.includes('copiedRows.name ? "已复制" : "复制"') || !ui.includes('copiedRows.tunnel ? "已复制" : "复制"')) throw new Error("LB-016 copy feedback is not stable three-second per row");
for (const step of [2,3,4,5]) if (!ui.includes(`setStep(${step-1})`)) throw new Error(`LB-016 Screen ${step} lacks back path`);
for (const label of ["本地运行环境","编码服务","OpenAI Tunnel"]) if (!ui.includes(`label="${label}"`)) throw new Error(`LB-016 Screen5 check missing: ${label}`);
if (!readiness.includes("ServiceStatusDot")) throw new Error("LB-016 Screen5 does not share typed status-dot presentation");
for (const text of ["等待检查","正在检查","已通过","需要处理"]) if (!readiness.includes(text)) throw new Error(`LB-016 Screen5 status wording missing: ${text}`);
if (!existsSync("tests/e2e/onboarding/fixed_window_runtime_e2e.mjs")) throw new Error("LB-016 real fixed-window E2E missing");
for (const command of ["get_onboarding_state","save_onboarding_connection","choose_onboarding_workspace_folder","open_chatgpt_plugins_settings","open_chatgpt_custom_connector_settings","complete_onboarding"]) {
  const start = backend.indexOf('pub async fn ' + command);
  if (start < 0) throw new Error('LB-016 blocking onboarding Tauri command remains: ' + command);
  const next = backend.indexOf('pub async fn ', start + 12);
  const body = backend.slice(start, next < 0 ? backend.length : next);
  if (!body.includes('spawn_blocking')) throw new Error('LB-016 onboarding command lacks worker boundary: ' + command);
}
const latest=auth.records.find(r=>r.authorization_id==="EXEC-PREAUTH-LB016-014"); if(!latest || latest.user_audit_status!=="PENDING") throw new Error("LB-016 historical authorization audit state changed");
console.log("LB016_CONTRACT=PASS screens=5 saved_connection_projection=length_only runtime_key_plaintext_frontend=false saved_key_mask=length_exact untouched_mask_retained=true backend_owned_readiness=true wake_driven_projection=true ui_blocking_boundary=true admin_selection_uac=true permission_geometry=runtime_gated screen4_exact=true screen5_shared_typed_state=true human_visual_gate=pending");
